### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by alexzk1** [CmdrVasquess/bcplus#11]
And how to build that ? 
using "make all" does not do.
Also except already existing copies I managed to get 

main.go:10:2: cannot find package "github.com/CmdrVasquess/BCplus/core" in any of:

then doing "go get" made more errors ... damn it, not saying it creates ~/home/go which I don't like to have ...

**Comment by CmdrVasquess** [comment]
Whooha, I'm late! At least its not yet a full year :(
Anyway. Since then I started to use the Go module system. And when using it a simple `go build` in the project's root did the trick for me (on Linux, I did not build on Win for quite some time… don't ask. But I'm a Linux guy)

**Comment by CmdrVasquess** [comment]
With Go modules build works as described in the README
