### ISSUE TITLE
Program gets confused about user folders

### ISSUE THREAD

**Issue by necros0** [CmdrVasquess/bcplus#7]
From the log file:

> bcplus:2018/02/25 10:57:18 assets: D:\Games\Elite Dangerous Mods\BCplus\bcplus.d
bcplus:2018/02/25 10:57:18 BoardComputer+ v0.4.7Î± / go1.10 on windows (So 25. Feb 12:45:28 CET 2018)
bcplus:2018/02/25 10:57:18 data    : D:\Users\username\bcplus
bcplus:2018/02/25 10:57:18 journals: C:\Users\username\Saved Games\Frontier Developments\Elite Dangerous
bcplus:2018/02/25 10:57:18 cannot read macros: open D:\Users\username\bcplus\macros.xsx: The system cannot find the file specified.
bcplus:2018/02/25 10:57:18 Starting web GUI on port 1337
bcplus:2018/02/25 10:57:18 starting main event loopâ€¦
bcplus:2018/02/25 10:57:18 cannot watch C:\Users\username\Saved Games\Frontier Developments\Elite Dangerous: GetFileAttributes: The system cannot find the path specified.

The first path is correct "D:\Users\username\bcplus", but subsequent ones looking on C: are wrong.  Those folders do not exist there, but are present in D:\Users\username\

**Comment by CmdrVasquess** [comment]
OK! I assumed the E:D installation on C: – Will fix it using the home directory for the journal path.
Until a fix is available I'd suggest you use the '-j' command line option
