### ISSUE TITLE
Please don't upshift StarSystem names in EDDN messages.

### ISSUE THREAD

**Issue by bgol** [CmdrVasquess/bcplus#9]
Can you please not upshift the name of the Starsystems you send to EDDN. My listener is not always running, so a Scan event could be the first encounter of the system which then will get saved in UPPER case (it's nitpicking I know, but I prefer the mixed case).

**Comment by CmdrVasquess** [comment]
Ok, sorry for looking here rarely. So you prefer the names as they come from the game, I think?! So I will try to upcase them only for BC+. 
By the way. I assume you use a version that you built yourself? I never made a binary release that sends to EDDN (AFAIR).

**Comment by CmdrVasquess** [comment]
Commit d0faee1d3f95dd829b6fc844968d1c652bdc37e8 will not introduce any new upcase'd names into BC+. However there is no implementation to “downcase” names in the galaxy.db. However the new rewrite does not have any binary releases and is not in wide use. (For my own galaxy.db I used data from EDSM to patch the names)
